spring:
  application:
    name: smartpark
  datasource:
    url: jdbc:h2:mem:smartpark-dev-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

server:
  port: 8080